### ISSUE TITLE
pin protection for withdrawal

### ISSUE THREAD

**Issue by krisha** [hackerspace-bootstrap/strichliste-web#50] opened 2015-02-09 22:33 UTC

**Comment by schinken** [comment] 2015-02-10 07:43
Related to https://github.com/hackerspace-bootstrap/strichliste/issues/3

**Comment by schinken** [comment] 2016-01-05 18:46
closed because of duplicate of #3

**Comment by schinken** [comment] 2018-08-30 10:06
Also a won't fix in strichliste 2. Sry

**Closed by schinken** 2018-08-30 10:06 UTC
